### ISSUE TITLE
Error on SSR (window is not defined)

### ISSUE THREAD

**Issue by firstpersoncode** [locize/i18next-locize-backend#305]
Hi,
I tried to build React app with SSR, and with `i18next-locize-backend` for localization.
When I tried to initialized `i18next` instance in my server file, I got this error:

```bash
/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/i18next-locize-backend/dist/cjs/i18nextLocizeBackend.js:175
      var hostname = window.location && window.location.hostname;
                     ^

ReferenceError: window is not defined
    at I18NextLocizeBackend.init (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/i18next-locize-backend/dist/cjs/i18nextLocizeBackend.js:175:22)
    at new I18NextLocizeBackend (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/i18next-locize-backend/dist/cjs/i18nextLocizeBackend.js:157:12)
    at createClassOnDemand (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/i18next/dist/cjs/i18next.js:1834:57)
    at I18n.init (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/i18next/dist/cjs/i18next.js:1861:44)
    at Object.init (/Users/nassermaronie/dev/my-react-kit/dev2.1/src/__app__/i18n.ts:53:10)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._compile (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.newLoader [as .ts] (/Users/nassermaronie/dev/my-react-kit/dev2.1/node_modules/pirates/lib/index.js:104:7)
```

This is due this line, where it doesn't check wether the window object is exist or undefined:
https://github.com/locize/i18next-locize-backend/blob/121df282b4d8db9fa5d689f14f526934bae85d0c/src/index.js#L71

And this is my server file where I initialized the `i18next` instance with my `locizeConfigs`:
```jsx
import React from 'react'
import express from 'express'
import path from 'path'
import fs from 'fs'
import i18next from 'i18next'
import Locize from 'i18next-locize-backend'
import { I18nextProvider } from 'react-i18next'
import { StaticRouter, matchPath } from 'react-router-dom'
import { renderToString } from 'react-dom/server'

import App from './App'

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)
const appSrc = resolveApp('src')

const assets = require(process.env.APP_MANIFEST)
const i18nextMiddleware = require('i18next-express-middleware')

const server = express()

const locizeConfigs = {
    projectId: process.env.APP_LOCIZE_PROJECT_ID,
    apiKey: process.env.APP_LOCIZE_API_KEY,
    referenceLng: process.env.APP_LANG,
    private: true,
    allowedAddOrUpdateHosts: ['localhost'],
}

i18next
  .use(Locize)
  .use(i18nextMiddleware.LanguageDetector)
  .init(
    {
      debug: false,
      preload: ['en', 'de'],
      ns: ['translations'],
      defaultNS: 'translations',
      backend: locizeConfigs,
    },
    () => {
      server
        .disable('x-powered-by')
        .use(i18nextMiddleware.handle(i18next))
        .use('/locales', express.static(`${appSrc}/locales`))
        .use(express.static(process.env.APP_PUBLIC_DIR))
        .get('/*', (req, res) => {
          const context = {}
          const markup = renderToString(
            <I18nextProvider i18n={req.i18n}>
              <StaticRouter context={context} location={req.url}>
                <App />
              </StaticRouter>
            </I18nextProvider>,
          )

          const { url } = context
          if (url) {
            res.redirect(url)
          } else {
            const initialI18nStore = {}
            req.i18n.languages.forEach(l => {
              initialI18nStore[l] = req.i18n.services.resourceStore.data[l]
            })
            const initialLanguage = req.i18n.language

            res.status(200).send(
              `<!doctype html>
        <html lang="">
        <head>
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta charSet='utf-8' />
            <title>Welcome</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            ${assets.client.css ? `<link rel="stylesheet" href="${assets.client.css}">` : ''}
            <script src="${assets.client.js}" defer></script>
            <script>
              window.initialI18nStore = JSON.parse('${JSON.stringify(initialI18nStore)}');
              window.initialLanguage = '${initialLanguage}';
            </script>
        </head>
        <body>
            <div id="root">${markup}</div>
        </body>
    </html>`,
            )
          }
        })
    },
  )

export default server
```

**Comment by jamuhl** [comment]
This backend is not universal...like in next-i18next on server you will have to use a different backend than for the client: https://github.com/locize/i18next-node-locize-backend

**Comment by Vadorequest** [comment]
This creates tons of problems on universal apps, couldn't an effort be made to have one backend that is universal instead of dynamically loading https://github.com/locize/i18next-locize-backend or https://github.com/locize/i18next-node-locize-backend?

**Comment by jamuhl** [comment]
Could be possible in the future...guess we will do so as soon a more mature solution from next-i18next side evolves regarding usage in serverless (for now consuming locize resources is no problem...just use the API routes -> the locize-backend is nothing more than a extended xhr-backend)

**Comment by adrai** [comment]
IMO: client-side and server-side behave not the same and they should not do the same.
The client has the chance to work with cache etc... but the serverside not (there is a configurable reload interval)
Especially when using in a serverless environment this makes even more problem.
That’s why we advice to bundle the translations with the serverless code. See: https://github.com/locize/i18next-node-locize-backend/blob/master/README.md#important-advice-for-serverless-environments---aws-lambda-google-cloud-functions-azure-functions-etc

**Comment by Vadorequest** [comment]
Fixed by https://github.com/locize/i18next-locize-backend/commit/621b711d2948845bcf97161a7aca5093c76f2ce2
