### ISSUE TITLE
Jest open handles 

### ISSUE THREAD

**Issue by Maxim-Filimonov** [locize/i18next-locize-backend#345]
## 🐛 Bug Report
Jest detects open handle after plugin registration:
```
●  TLSWRAP
      26 |     .use(Locize)
      27 |     .use(new LanguageDetector({}, hapiRequestOverrides))
    > 28 |     .init(options)
         |      ^
      29 |     .then(() => i18next)
      30 |
      31 | exports.plugin = {
      at I18n.init (node_modules/i18next/dist/cjs/i18next.js:2350:9)
      at init (lib/i18next.js:28:6)
      at Object.register (lib/i18next.js:33:24)
```
## To Reproduce
plugin.js
```js
const middleware = require('i18next-http-middleware')
const i18next = require('i18next')
const Locize = require('i18next-locize-backend')
var { LanguageDetector } = require('i18next-http-middleware')
let options = {
 preload: ['en-AU', 'zh'],
 fallbackLng: 'en-AU',
 ns: ['backend'],
 backend: {
 projectId: 'PROJECT_ID',
 apiKey: 'LOCIZE_KEY',
 referenceLng: 'en-AU',
 },
}
const init = () =>
 i18next
 .use(Locize)
 .use(new LanguageDetector({})
 .init(options)
 .then(() => i18next)
exports.plugin = {
register: async (server, options) => {
const i18n = await init()
const i18nextMiddleware = middleware.handle(i18n)
 server.ext('onPreHandler', (request, h) => {
i18nextMiddleware(request, false, () => {
return true
 })
return h.continue
 })
 },
 name: 'i18next',
 pkg: require('../package.json'),
 version: require('../package.json').version,
}
```
plugin.test.js:
```js
const { plugin } = require('../../lib/i18next')
class ServerMock {
  constructor() {
    this.extensions = {}
    this.methods = {}
  }
  ext(name, func) {
    this.extensions[name] = func
  }
  method(name, func) {
    this.methods[name] = func
  }
}
describe('i18n', () => {
  let server
  const handler = { continue: jest.fn() }
  beforeAll(async () => {
    server = new ServerMock()
    await plugin.register(server)
  })
  it('can translate using request t function', () => {
    const request = {}
    server.extensions['onPreHandler'](request, handler)
    expect(request.i18n).not.toBeNull()
    expect(request.t('test_translation_check')).toEqual('test')
  })
})
```
Run with `npm run jest --detectOpenHandles`

## Expected behavior
Expected i18n to not hold to handle after test finish or at least provide a method to cleanup any hold connections 

## Your Environment
- *runtime version*: v14.18.2
- *module version*: 21.6.6
- *os*: Mac
- jest: 27.4.7

**Comment by adrai** [comment]
This is probably because of the setInterval... if the problem is in this module...
try to set the reloadInterval option to false: https://github.com/locize/i18next-locize-backend#backend-options

**Comment by Maxim-Filimonov** [comment]
Hm... I tried this setting:
```
let options = {
 preload: ['en-AU', 'zh'],
 fallbackLng: 'en-AU',
 ns: ['backend'],
 backend: {
 reloadInterval: false,
 projectId: 'PROJECT_ID',
 apiKey: 'LOCIZE_KEY',
 referenceLng: 'en-AU',
 },
}
  ```
  It doesn't seem to work. After debugging through the code the code where setInterval is used it seem that reloadInterval is always overloaded with default parameters.

**Comment by Maxim-Filimonov** [comment]
It actually is pointing to [this code](https://github.com/i18next/i18next/blob/master/src/i18next.js#L212). I'll move issue to the core repository then.

**Comment by adrai** [comment]
I don't think the main problem is in the core repository...
Can you please provide a reproducible github repo or similar, so I can check it?

**Comment by Maxim-Filimonov** [comment]
Added [repo](https://github.com/Maxim-Filimonov/i18n_tlswap_issue)

**Comment by adrai** [comment]
It looks to be a jest problem when consuming http connections...
for example if you do this test:

```js
it("can translate using request t function", async () => {
    await fetch('https://go-vip.net/ip-ranges.json')
     .then((r) => {
       expect(r.status).toBe(200);
     })
     .catch((e) => {
       fail(e);
     });
  });
```

it will also fail with TLSWRAP...

btw: during test I would not recommend to consume the locize CDN...
You could do something like this:

```js
const middleware = require("i18next-http-middleware");
const i18next = require("i18next");
const Locize = require("i18next-locize-backend");
var { LanguageDetector } = require("i18next-http-middleware");

const areWeTestingWithJest = process.env.JEST_WORKER_ID !== undefined;

let options = {
  preload: ["en-AU", "zh"],
  fallbackLng: "en-AU",
  ns: ["backend"],
  backend: {
    projectId: "PROJECT_ID",
    apiKey: "LOCIZE_KEY",
    referenceLng: "en-AU",
  },
};

if (areWeTestingWithJest) {
  options.resources = {
    'en-AU': {
      backend: {
        some: 'translation resources'
      }
    }
  }
}

const init = () => areWeTestingWithJest ?
  i18next
    .use(LanguageDetector)
    .init(options)
    .then(() => i18next) :
  i18next
    .use(Locize)
    .use(LanguageDetector)
    .init(options)
    .then(() => i18next);

exports.plugin = {
  register: async (server, options) => {
    const i18n = await init();
    const i18nextMiddleware = middleware.handle(i18n);
    server.ext("onPreHandler", (request, h) => {
      i18nextMiddleware(request, false, () => {
        return true;
      });
      return h.continue;
    });
  },
  name: "i18next",
};

```

**Comment by Maxim-Filimonov** [comment]
Thanks for the hint! That did work without any issues now and all my test pass thank you! 😊
